# Generated by Django 3.2.12 on 2022-03-12 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='data',
            new_name='date',
        ),
    ]
